import React from 'react';
import ReactDOM from 'react-dom';
import './index.scss';
import App from './App.jsx';
import 'normalize.css';
import 'bootstrap/dist/css/bootstrap.min.css';
import 'bootstrap';
import 'lightbox2/src/css/lightbox.css';
import 'lightbox2/src/js/lightbox.js';
ReactDOM.render( < App / > , document.getElementById('root'));